export const PK_CITIES = [
  "Karachi",
  "Lahore",
  "Islamabad",
  "Rawalpindi",
  "Faisalabad",
  "Multan",
  "Peshawar",
  "Quetta",
  "Gujranwala",
  "Sialkot",
  "Hyderabad",
  "Bahawalpur",
  "Sargodha",
  "Sukkur",
  "Larkana",
  "Sheikhupura",
  "Rahim Yar Khan",
  "Jhang",
  "Mardan",
  "Gujrat",
  "Kasur",
  "Dera Ghazi Khan",
  "Sahiwal",
  "Okara",
  "Wah Cantonment",
  "Mingora",
  "Abbottabad",
  "Kohat",
  "Jhelum",
  "Khanewal",
  "Chiniot",
  "Nawabshah",
  "Mirpur Khas",
  "Muzaffargarh",
  "Kamoke",
  "Mandi Bahauddin",
  "Mansehra",
  "Attock",
  "Vehari",
  "Kotli",
  "Gilgit",
  "Skardu",
  "Chitral",
  "Gwadar",
  "Muzaffarabad",
] as const;
