-- Closet by Junassan — schema bootstrap
--
-- The schema now lives as numbered migrations under supabase/migrations/.
-- Run them in order in the Supabase SQL editor:
--
--   1. supabase/migrations/0001_init.sql
--   2. supabase/migrations/0002_rls.sql
--   3. supabase/migrations/0003_create_order_rpc.sql
--
-- RLS is default-deny on orders/order_items/contact_messages/subscribers.
-- All writes go through SUPABASE_SERVICE_ROLE_KEY on the server (never in
-- the browser). Anon can only SELECT from products.
